kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-newns-sept17-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: test-newns-sept17-dsp-job
    namespace: rhtap-app-development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-newns-sept17-dsp-job-role